
# Reserved channels:
# command       used for keyboard commands
# so these channels should not be used in inputs or outputs below
udp_monitor:
    type: udp_monitor
    input: to_monitor
    server_address: 192.168.1.166:8004

udp_remote_compass:
    type:  udp_listen
    outputs:
        - to_head_resolve
    port: 8005

compass_resolve:
    type: compass_resolver
    input:
        to_head_resolve
    outputs:
      - to_log
      - to_udp_autohelm
      - to_2000
      - to_udp_client

compass:
    name: /dev/ttyUSB0
    type: serial
    baud:  4800
    outputs:
      - to_head_resolve

bridge:
    name: /dev/ttyUSB1
    type: serial
    baud: 38400
    input: to_2000
    outputs:
      - to_log
      - to_udp_client


ais:
    name: /dev/ttyUSB3
    type: serial
    baud: 38400
    outputs:
      - to_2000
      - to_udp_client

log:
    type: ships_log
    input: to_log

udp_opencpn:
    type:  udp_client
    input: to_udp_client
    server_address: 192.168.1.14:8011

udp_autohelm:
    type:  udp_client
    input: to_udp_autohelm
    server_address: 127.0.0.0:8007

