
# Reserved channels:
# command       used for keyboard commands
# so these channels should not be used in inputs or outputs below
compass:
    name: /dev/ttyUSB0
    type: serial
    baud:  4800
    outputs:
      - to_log
      - to_helm
      - to_2000
      - to_udp_client

bridge:
    name: /dev/ttyUSB1
    type: serial
    baud: 38400
    input: to_2000
    outputs:
      - to_log
      - to_udp_client


ais:
    name: /dev/ttyUSB3
    type: serial
    baud: 38400
    outputs:
      - to_2000
      - to_udp_client

log:
    type: ships_log
    input: to_log

udp:
    type:  udp_client
    input: to_udp_client
    server_address: 192.168.1.14:8011

helm:
    type: auto-helm
    p_factor: 100
    i_factor: 100
    d_factor: 100
    gain_factor: 100
    input: to_helm

keys:
    type: keyboard
    outputs: 
        - to_helm


